
import { ProductModel } from "./my-products.model";

export const ELECTRONICS_PRODUCTS: ProductModel[] = [
  {
    productName: 'Samsung Smart TV',
    brand: 'Samsung',
    model: 'QLED Q60T',
    category: 'Television',
    price: 1200,
    available: true,
    description:
      'Samsung QLED TV with Quantum Dot technology for rich colors and high image clarity. Supports 4K resolution.',
    features: [
      'Screen size: 55 inches',
      'Resolution: 4K',
      'Smart TV (Tizen OS)',
      'HDR support',
      'Quantum Dot technology',
    ],
    profileImageUrl: '/img/samsung-tv.webp',
    originCountry: 'South Korea',
    warrantyYears: 2,
    qtty: 1,
  },
  {
    productName: 'LG Washing Machine',
    brand: 'LG',
    model: 'FH4G1JCH2N',
    category: 'Washing Machine',
    price: 850,
    available: true,
    description:
      'LG washing machine with Steam Wash and Inverter Direct Drive technology for energy-efficient and quiet washing.',
    features: [
      'Load capacity: 10 kg',
      'Spin speed: 1400 rpm',
      'Inverter Direct Drive technology',
      'Steam washing function',
      'Smart control via smartphone',
    ],
    profileImageUrl: '/img/lg-washing-machine.webp',
    originCountry: 'South Korea',
    warrantyYears: 3,
    qtty: 1,
  },
  {
    productName: 'Bosch Refrigerator',
    brand: 'Bosch',
    model: 'KGN36XI42',
    category: 'Refrigerator',
    price: 1100,
    available: false,
    description:
      'Energy-efficient Bosch refrigerator with A+++ rating and NoFrost technology, making food storage easier without the need for defrosting.',
    features: [
      'Capacity: 324 liters',
      'NoFrost technology',
      'Energy efficiency class: A+++',
      'Electronic control',
      'Noise level: 39 dB',
    ],
    profileImageUrl: '/img/bosch-fridge.webp',
    originCountry: 'Germany',
    warrantyYears: 2,
    qtty: 1,
  },
  {
    productName: 'Dyson Vacuum Cleaner',
    brand: 'Dyson',
    model: 'V11 Absolute',
    category: 'Vacuum Cleaner',
    price: 600,
    available: false,
    description:
      'The Dyson V11 cordless vacuum cleaner with a powerful digital motor and filtration system for maximum cleaning efficiency.',
    features: [
      'Suction power: 185 AW',
      'Battery life: up to 60 minutes',
      'HEPA filter',
      '3 operating modes',
      'Bagless',
    ],
    profileImageUrl: '/img/dyson-vacuum.webp',
    originCountry: 'United Kingdom',
    warrantyYears: 2,
    qtty: 1,
  },
  {
    productName: 'Apple MacBook Pro',
    brand: 'Apple',
    model: 'M1 Pro',
    category: 'Laptop',
    price: 2200,
    available: true,
    description:
      'Powerful Apple MacBook Pro with M1 Pro chip, ideal for professional tasks, offering high performance and long battery life.',
    features: [
      'Display: 14-inch Retina',
      'Processor: M1 Pro',
      'RAM: 16GB',
      'SSD storage: 512GB',
      'Battery life: up to 17 hours',
    ],
    profileImageUrl: '/img/macbook-pro.webp',
    originCountry: 'USA',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Sony PlayStation 5',
    brand: 'Sony',
    model: 'PS5',
    category: 'Game Console',
    price: 500,
    available: true,
    description:
      'Next-generation console from Sony supporting 4K games and fast loading times thanks to the built-in SSD.',
    features: [
      'Supports 4K gaming',
      'Built-in 825GB SSD',
      'Fast loading mode',
      'Backward compatibility with PS4 games',
      'DualSense controller',
    ],
    profileImageUrl: '/img/ps5.webp',
    originCountry: 'Japan',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Bose QuietComfort 45',
    brand: 'Bose',
    model: 'QC45',
    category: 'Headphones',
    price: 329,
    available: true,
    description:
      'Bose QuietComfort 45 wireless noise-cancelling headphones for immersive sound and clear voice calls.',
    features: [
      'Active noise cancellation',
      'Up to 24 hours battery life',
      'Bluetooth 5.1',
      'Comfortable ear cushions',
      'USB-C charging',
    ],
    profileImageUrl: '/img/bose-qc45.jpg',
    originCountry: 'USA',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Canon EOS R5',
    brand: 'Canon',
    model: 'R5',
    category: 'Camera',
    price: 3900,
    available: true,
    description:
      'Canon EOS R5 mirrorless camera with 45MP full-frame sensor, 8K video recording, and dual pixel autofocus.',
    features: [
      'Resolution: 45 MP',
      '8K video recording',
      'Dual Pixel CMOS AF II',
      'In-body image stabilization',
      'Wi-Fi and Bluetooth connectivity',
    ],
    profileImageUrl: '/img/canon.webp',
    originCountry: 'Japan',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'JBL Xtreme 3',
    brand: 'JBL',
    model: 'Xtreme 3',
    category: 'Bluetooth Speaker',
    price: 350,
    available: true,
    description:
      'JBL Xtreme 3 portable Bluetooth speaker with powerful sound, IP67 waterproof rating, and 15 hours of playtime.',
    features: [
      'Powerful sound with deep bass',
      'IP67 waterproof and dustproof',
      'Up to 15 hours of battery life',
      'Bluetooth 5.1',
      'PartyBoost feature',
    ],
    profileImageUrl: '/img/jbl.jpg',
    originCountry: 'USA',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Nintendo Switch OLED',
    brand: 'Nintendo',
    model: 'OLED Model',
    category: 'Game Console',
    price: 350,
    available: true,
    description:
      'Nintendo Switch OLED model with a vibrant 7-inch OLED screen for enhanced gaming experience.',
    features: [
      '7-inch OLED screen',
      '64GB internal storage',
      'Handheld, TV, and Tabletop modes',
      'Supports up to 1080p resolution on TV',
      'Joy-Con controllers',
    ],
    profileImageUrl: '/img/nintendo.jpg',
    originCountry: 'Japan',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Fitbit Charge 5',
    brand: 'Fitbit',
    model: 'Charge 5',
    category: 'Fitness Tracker',
    price: 180,
    available: true,
    description:
      'Fitbit Charge 5 fitness tracker with advanced health metrics, built-in GPS, and sleep tracking.',
    features: [
      'Built-in GPS',
      'Health metrics like heart rate and SpO2',
      'Sleep tracking',
      'Stress management tools',
      'Up to 7 days of battery life',
    ],
    profileImageUrl: '/img/fitbit.webp',
    originCountry: 'USA',
    warrantyYears: 1,
    qtty: 1,
  },
  {
    productName: 'Google Nest Hub Max',
    brand: 'Google',
    model: 'Nest Hub Max',
    category: 'Smart Display',
    price: 229,
    available: true,
    description:
      'Google Nest Hub Max with a 10-inch HD display and built-in Google Assistant for smart home control and entertainment.',
    features: [
      '10-inch HD touchscreen',
      'Built-in Google Assistant',
      'Video calling with Nest Cam',
      'Compatible with smart home devices',
      'Stereo speakers',
    ],
    profileImageUrl: '/img/nesthub.jpg',
    originCountry: 'USA',
    warrantyYears: 1,
    qtty: 1,
  },

];
